version: '2.0'

#To be run on choralcluster4 (172.18.2.104)
services:
  cassandra:
    container_name: cassandra
    hostname: cassandra
    image: cassandra
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
      - "9142:9142"
    volumes:
      - /network/seng466_shared/persistent/cassandra:/var/lib/cassandra:rw
    networks:
      - choralstorm

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /network/seng466_shared/persistent/redis/data:/data
    networks:
      - choralstorm

networks:
  choralstorm:
    external: true