version: '3.2'

services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      - choralstorm

  kafka:
    container_name: kafka
    hostname: kafka
    image: kafka
    ports:
      - "9092:9092"
    networks:
      - choralstorm
    links:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      # Update this to "kafka" if we find out how
      KAFKA_ADVERTISED_HOST_NAME: localhost
    depends_on:
      - zookeeper

  nimbus:
    container_name: nimbus
    command: storm nimbus
    hostname: nimbus
    image: storm
    ports:
      - "6627:6627"
      - "3772"
      - "3773"
      - "3774"
    networks:
      - choralstorm
    links:
      - zookeeper
      - cassandra
      - redis
    volumes:
      - /root/workspace:/root/workspace
    depends_on:
      - zookeeper

  supervisor:
    container_name: supervisor
    command: storm supervisor
    hostname: supervisor
    image: storm
    ports:
      - "6700:6700"
      - "6701:6701"
      - "6702:6702"
      - "6703:6703"
      - "8000:8000"
    networks:
      - choralstorm
    links:
      - nimbus
      - zookeeper
      - cassandra
      - redis
    depends_on:
      - zookeeper
      - nimbus

  ui:
    container_name: ui
    command: storm ui
    hostname: ui
    image: storm
    ports:
      - "8080:8080"
    networks:
      - choralstorm
    links:
      - cassandra
      - redis
    depends_on:
      - zookeeper
      - nimbus
      - supervisor

  cassandra:
    container_name: cassandra
    hostname: cassandra
    image: cassandra
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
      - "9142:9142"
    networks:
      - choralstorm

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - choralstorm

networks:
  choralstorm:
    external: true