version: '2.0'

services:
  zookeeper:
    container_name: ChoralStorm-zookeeper
    hostname: zookeeper
    image: zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      - choralstorm

  kafka:
    container_name: ChoralStorm-kafka
    hostname: kafka
    image: kafka
    ports:
      - "9092:9092"
    networks:
      - choralstorm
    links:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      # Edit this to your machine's local ip address
      # This is a temporary solution, another solution is to use "kafka" as host name
      # and edit the /etc/hosts file: 127.0.0.1   kafka
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.14
    depends_on:
      - zookeeper

  nimbus:
    container_name: ChoralStorm-nimbus
    command: storm nimbus
    hostname: nimbus
    image: storm
    ports:
      - "6627:6627"
      - "3772"
      - "3773"
      - "3774"
    networks:
      - choralstorm
    links:
      - zookeeper
      - cassandra
      - redis
    volumes:
      - /root/workspace:/root/workspace
    depends_on:
      - zookeeper

  supervisor:
    container_name: ChoralStorm-supervisor
    command: storm supervisor
    hostname: supervisor
    image: storm
    ports:
      - "6700:6700"
      - "6701:6701"
      - "6702:6702"
      - "6703:6703"
      - "8000:8000"
    networks:
      - choralstorm
    links:
      - nimbus
      - zookeeper
      - cassandra
      - redis
    depends_on:
      - zookeeper
      - nimbus

  ui:
    container_name: ChoralStorm-ui
    command: storm ui
    hostname: ui
    image: storm
    ports:
      - "8000:8000"
    networks:
      - choralstorm
    links:
      - cassandra
      - redis
    depends_on:
      - zookeeper
      - nimbus
      - supervisor

  cassandra:
    container_name: ChoralStorm-cassandra
    hostname: cassandra
    image: cassandra
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
      - "9142:9142"
    #volumes:
    #  - /network/seng466_shared/cassandra:/var/lib/cassandra:rw
    networks:
      - choralstorm

  redis:
    container_name: ChoralStorm-redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    #volumes:
    #  - /network/seng466_shared/redis/data:/data
    networks:
      - choralstorm

  elasticsearch:
      container_name: ChoralStorm-elasticsearch
      hostname: elasticsearch
      image: elasticsearch
      ports:
        - "9200:9200"
        - "9300:9300"
      #volumes:
      #  - /network/seng466_shared/elasticsearch/data:/usr/share/elasticsearch/data
      networks:
        - choralstorm

networks:
  choralstorm:
    external: true
